name: path_finder
description: A sample command-line application.
version: 0.0.1
homepage: https://github.com/dartclub/path_finder

environment:
  sdk: '>=2.17.5 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  dartclub_lint: ^0.4.2
  test: ^1.16.0
